### ISSUE TITLE
Telefon Defteri

### ISSUE THREAD

**Issue by barisener** [KaygusuzBK/ConsoledanNerelere#3]
İlk olarak bu bi telefon defteri olmamış :D not defteri olmuş. 

Bunu önce 
- Kişi adı
- Telefon no
alacak şekilde düzenleyelim.

Sonra
- Kişi adıyla silinebilir hale getirelim.

**Comment by barisener** [comment]
@KaygusuzBK elinden öper

**Comment by KaygusuzBK** [comment]
telefon defteri demedim ki not defteri dedim zaten :) 
Tamamdır 👍
